---
# installation method from: https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository
- name: "Install yum-utils"
  package:
    name: yum-utils
    state: present

- name: "Adding Docker CE repo via yum-utils"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo creates=/etc/yum.repos.d/docker-ce.repo
