---
# http://docs.ansible.com/ansible/apt_key_module.html
- name: "Install Docker repo apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# http://docs.ansible.com/ansible/apt_repository_module.html
- name: "Install Docker apt repo for {{ansible_distribution}}/{{ansible_distribution_release}}"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}}  stable
    state: present
